### ISSUE TITLE
Code typo in Bootstrapexample.R

### ISSUE THREAD

**Issue by aegerton** [djhindley/shiny-server#1]
@djhindley Line 40 has an extra 2 in the BootChainLadder function call      

`Boot2<-BootChainLadder2(GenIns, 5000,process.dist=c("gamma"))`

**Comment by djhindley** [comment]
Many Thanks, Anthony. It is a while since I wrote this code, but I will look into this issue and post an update in due course.

**Comment by aegerton** [comment]
@djhindley, thank you. I am enjoying working my way through the book!

**Comment by djhindley** [comment]
Now corrected.  The code in the book itself in Appendix B is correct; it was just the code on Github that was wrong.  Thanks to aegerton for pointing this out.

**Comment by djhindley** [comment]
Anthony

Now corrected.  Many thanks for spotting this.  Hope you continue to enjoy
the book.

Kind Regards

David.

**Comment by aegerton** [comment]
Thank you, David.  I am sure I will!
